# Generated by Django 3.2.4 on 2021-06-06 03:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color1',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='color2',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='color3',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True),
        ),
    ]
