# Generated by Django 3.2.4 on 2021-06-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210608_0809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Figma', 'Figma'), ('XD', 'XD'), ('Bootstrap', 'Bootstrap'), ('Skectch', 'Sketch')], default='Figma', max_length=255),
        ),
    ]
