# Generated by Django 3.2.4 on 2021-06-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210608_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Figma', 'Figma'), ('XD', 'XD'), ('Bootstrap', 'Bootstrap'), ('Sketch', 'Sketch')], default='Figma', max_length=255),
        ),
    ]
