# Generated by Django 3.2.4 on 2021-06-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Figma', 'Figma'), ('XD', 'XD')], default='Figma', max_length=255),
        ),
    ]
