# Generated by Django 3.2.4 on 2021-06-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[], default='Figma', max_length=255),
        ),
    ]
